[package]
name = "task-runner-tui"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.25.0", features = ["full"] }
turborepo-ui = { path = "vendor/turborepo/crates/turborepo-ui" }
turbopath = { path = "vendor/turborepo/crates/turborepo-paths" }
rust-ini = "0.21.3"
